#!/usr/bin/env python

import os
from tokens import create_app
from flask import Flask
from flask.ext.script import Manager, Shell

app = Flask(__name__)

manager = Manager(app)

@manager.shell
def make_shell_context():
	return dict(app=app)


if __name__ == '__main__':
	manager.run()