#!/bin/sh
#
# Orient the execution of the manage script relative to be base of our distribution
#

CANONPATH=`readlink -f $0`
BASE=`dirname $CANONPATH`
cd $BASE

. venv/bin/activate

exec python manage $*